FROM postgres:latest


# TODO: REMOVE THESE LINES IN PRODUCTION 
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=jidfkwshfj9o234hi4uoh32o
ENV POSTGRES_DB=securearch

# Create a directory to mount as the PostgreSQL data directory
RUN mkdir -p /opt/postgres

# Set the mounted directory as the PostgreSQL data directory
VOLUME /opt/postgres

# Copy the custom pg_hba.conf into the container
COPY pg_hba.conf /etc/postgresql/

COPY setup.sql /docker-entrypoint-initdb.d/
EXPOSE 5432
