version: "3.8"

x-shared:
  zammad-service: &zammad-service
    environment: &zammad-environment
      MEMCACHE_SERVERS: ${MEMCACHE_SERVERS}
      POSTGRESQL_DB: ${POSTGRES_DB}
      POSTGRESQL_HOST: ${POSTGRES_HOST}
      POSTGRESQL_USER: ${POSTGRES_USER}
      POSTGRESQL_PASS: ${POSTGRES_PASS}
      POSTGRESQL_PORT: ${POSTGRES_PORT}
      POSTGRESQL_OPTIONS: ${POSTGRESQL_OPTIONS}
      POSTGRESQL_DB_CREATE: ${POSTGRESQL_DB_CREATE}
      REDIS_URL: ${REDIS_URL}
      S3_URL: ${S3_URL}
      BACKUP_DIR: ${BACKUP_DIR}
      BACKUP_TIME: ${BACKUP_TIME}
      HOLD_DAYS: ${HOLD_DAYS}
      TZ: ${TZ}
      AUTOWIZARD_JSON: ${AUTOWIZARD_JSON}
      AUTOWIZARD_RELATIVE_PATH: ${AUTOWIZARD_RELATIVE_PATH}
      ELASTICSEARCH_ENABLED: ${ELASTICSEARCH_ENABLED}
      ELASTICSEARCH_SCHEMA: ${ELASTICSEARCH_SCHEMA}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER}
      ELASTICSEARCH_PASS: ${ELASTICSEARCH_PASS}
      ELASTICSEARCH_NAMESPACE: ${ELASTICSEARCH_NAMESPACE}
      ELASTICSEARCH_REINDEX: ${ELASTICSEARCH_REINDEX}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      NGINX_SERVER_SCHEME: ${NGINX_SERVER_SCHEME}
      RAILS_TRUSTED_PROXIES: ${RAILS_TRUSTED_PROXIES}
      ZAMMAD_HTTP_TYPE: ${ZAMMAD_HTTP_TYPE}
      ZAMMAD_FQDN: ${ZAMMAD_FQDN}
      ZAMMAD_WEB_CONCURRENCY: ${ZAMMAD_WEB_CONCURRENCY}
      ZAMMAD_PROCESS_SESSIONS_JOBS_WORKERS: ${ZAMMAD_PROCESS_SESSIONS_JOBS_WORKERS}
      ZAMMAD_PROCESS_SCHEDULED_JOBS_WORKERS: ${ZAMMAD_PROCESS_SCHEDULED_JOBS_WORKERS}
      ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS: ${ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS}
      ZAMMAD_SESSION_JOBS_CONCURRENT: ${ZAMMAD_SESSION_JOBS_CONCURRENT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    image: ${IMAGE_REPO}:${VERSION}
    restart: ${RESTART}
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
    networks:
      - ticket_network

services:
  zammad-backup:
    <<: *zammad-service
    command: ["zammad-backup"]
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-storage:/opt/zammad/storage:ro
    user: 0:0

  zammad-elasticsearch:
    image: bitnami/elasticsearch:${ELASTICSEARCH_VERSION}
    restart: ${RESTART}
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    environment:
      ELASTICSEARCH_ENABLE_SECURITY: 'true'
      ELASTICSEARCH_SKIP_TRANSPORT_TLS: 'true'
      ELASTICSEARCH_ENABLE_REST_TLS: 'false'
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASS}
    networks:
      - ticket_network

  zammad-init:
    <<: *zammad-service
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    restart: on-failure
    user: 0:0

  zammad-memcached:
    command: memcached -m 256M
    image: memcached:${MEMCACHE_VERSION}
    restart: ${RESTART}
    networks:
      - ticket_network

  zammad-nginx:
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "${NGINX_PORT}"
    ports:
      - "0.0.0.0:${NGINX_EXPOSE_PORT}:${NGINX_PORT}"
    depends_on:
      - zammad-railsserver
    networks:
      - ticket_network

  zammad-postgresql:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    image: postgres:${POSTGRES_VERSION}
    restart: ${RESTART}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - ticket_network

  zammad-railsserver:
    <<: *zammad-service
    command: ["zammad-railsserver"]

  zammad-redis:
    image: redis:${REDIS_VERSION}
    restart: ${RESTART}
    volumes:
      - redis-data:/data
    networks:
      - ticket_network

  zammad-scheduler:
    <<: *zammad-service
    command: ["zammad-scheduler"]

  zammad-websocket:
    <<: *zammad-service
    command: ["zammad-websocket"]

volumes:
  elasticsearch-data:
    driver: local
  postgresql-data:
    driver: local
  redis-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-storage:
    driver: local

networks:
  ticket_network:
    external: true
    name: secure-arch_ticket_network