name: MQTT Agent CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-mqtt-agent:
    runs-on: ubuntu-latest
    name: MQTT Agent Build & Test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Python Syntax-Check
        run: |
          python -m py_compile app/shelly_door_v2.2.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build and push Agent image (multi-arch)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/secure-arch-mqtt-agent:latest \
            --push \
            ./app
          docker push ghcr.io/${{ github.repository_owner }}/secure-arch-mqtt-agent:latest

      - name: CI abgeschlossen
        run: echo "MQTT Agent CI erfolgreich abgeschlossen" 
