name: MQTT Agent CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-mqtt-agent:
    runs-on: ubuntu-latest
    name: MQTT Agent Build & Test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Python Syntax-Check
        run: |
          python -m py_compile app/shelly_door_v2.2.py

      - name: Docker Build and push Agent image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/secure-arch-mqtt-agent ./app
          docker push ghcr.io/${{ github.repository_owner }}/secure-arch-mqtt-agent:latest

      - name: Set GHCR package visibility to public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          PACKAGE_NAME: secure-arch-mqtt-agent
        run: |
          echo "Fetching versions for $PACKAGE_NAME..."
          
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/orgs/$REPO_OWNER/packages/container/$PACKAGE_NAME/versions")
          
          echo "Response:"
          echo "$RESPONSE"
          
          # Try to parse the first version ID
          VERSION_ID=$(echo "$RESPONSE" | jq 'if type=="array" and length>0 then .[0].id else empty end')
          
          if [[ -n "$VERSION_ID" ]]; then
            echo "Setting visibility of version $VERSION_ID to public..."
          
            PATCH_RESPONSE=$(curl -X PATCH -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d '{"visibility":"public"}' \
              "https://api.github.com/orgs/$REPO_OWNER/packages/container/$PACKAGE_NAME/versions/$VERSION_ID")
          
            echo "Patch response:"
            echo "$PATCH_RESPONSE"
          
          else
            echo "No versions found or unable to parse versions for $PACKAGE_NAME"
            exit 1
          fi

      - name: CI abgeschlossen
        run: echo "MQTT Agent CI erfolgreich abgeschlossen"
