name: MQTT Agent CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-mqtt-agent:
    runs-on: ubuntu-latest
    name: MQTT Agent Build & Test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Python Syntax-Check
        run: |
          python -m py_compile app/shelly_door_v2.2.py

      - name: Docker Build and push Agent image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/secure-arch-mqtt-agent ./app
          docker push ghcr.io/${{ github.repository_owner }}/secure-arch-mqtt-agent:latest

      - name: Debug token user (PAT_TOKEN)
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Token is for user:"
          curl -s -H "Authorization: Bearer $TOKEN" https://api.github.com/user | jq '.login'

      - name: Wait for package processing
        run: sleep 15

      - name: Set GHCR package visibility to public
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          PACKAGE_NAME: secure-arch-mqtt-agent
        run: |
          echo "Fetching versions for $PACKAGE_NAME..."
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/users/$REPO_OWNER/packages/container/$PACKAGE_NAME/versions")

          echo "Response:"
          echo "$RESPONSE" | jq .

          VERSION_ID=$(echo "$RESPONSE" | jq '.[0].id')

          if [[ "$VERSION_ID" != "null" ]]; then
            echo "Setting visibility of version $VERSION_ID to public..."
            PATCH_RESPONSE=$(curl -X PATCH -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d '{"visibility":"public"}' \
              "https://api.github.com/users/$REPO_OWNER/packages/container/$PACKAGE_NAME/versions/$VERSION_ID")

            echo "Patch response:"
            echo "$PATCH_RESPONSE" | jq .
          else
            echo "No versions found for $PACKAGE_NAME"
            exit 1
          fi

      - name: CI abgeschlossen
        run: echo "MQTT Agent CI erfolgreich abgeschlossen" 
